# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumohacks', '0002_auto_20160918_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='constipation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lumohacks.Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.IntegerField(null=True),
        ),
    ]
