# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumohacks', '0007_auto_20160918_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Bob', max_length=128),
            preserve_default=False,
        ),
    ]
