# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='blood_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnose',
            name='constipation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnose',
            name='diabetes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diagnose',
            name='smoking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='treatment',
            field=models.IntegerField(choices=[(0, 'Surgery'), (1, 'Chemotherapy'), (2, 'Radiation Therapy')]),
        ),
    ]
