# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_auto_20160918_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnose',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='diagnose',
            name='constipation',
        ),
        migrations.RemoveField(
            model_name='diagnose',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='diagnose',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnose',
            name='smoking',
        ),
    ]
